import Link from 'next/link';
import Image from 'next/image';
import { MessageCircle,ArrowUpRight } from 'lucide-react';
import { db } from '@/lib/db';
import { getSettings } from '@/lib/settings';
import { Header } from '@/components/navigation';
import { JsonLd } from '@/components/ui';
import { siteUrl,whatsapp } from '@/lib/utils';
export const dynamic='force-dynamic';
export async function generateMetadata(){const s=await getSettings();return {metadataBase:new URL(siteUrl()),title:{default:s.seoTitle,template:'%s | Rana Etiket'},description:s.seoDescription,icons:{icon:s.favicon},openGraph:{title:s.seoTitle,description:s.seoDescription,locale:'tr_TR',type:'website',siteName:s.company}};}
export default async function SiteLayout({children}:{children:React.ReactNode}){const[s,categories]=await Promise.all([getSettings(),db.category.findMany({where:{active:true},orderBy:{sortOrder:'asc'}})]);const wa=whatsapp(s.whatsapp);return <><a className="skip-link" href="#main">İçeriğe geç</a><div className="topbar"><div className="container"><span>Tasarımdan üretime, aynı özenle.</span><a href={`tel:${s.phone.replace(/[^+\d]/g,'')}`}>{s.phone}</a></div></div><Header logo={s.logo} links={s.menus.header} categories={categories} quote={wa}/><main id="main">{children}</main><footer><div className="container footer-grid"><div><Link href="/"><Image className="footer-logo" src={s.logo} alt={s.company} width={210} height={60}/></Link><p>{s.footer}</p><a className="text-link" href={wa} target="_blank" rel="noopener noreferrer">Projenizi konuşalım <ArrowUpRight size={17}/></a></div><div><h3>Ürünler</h3>{categories.map(c=><Link key={c.id} href={`/kategoriler/${c.slug}`}>{c.name}</Link>)}</div><div><h3>Kurumsal</h3>{s.menus.footer.map(([name,url])=><Link key={url} href={url}>{name}</Link>)}</div><div><h3>İletişimde kalalım</h3><a href={`tel:${s.phone.replace(/[^+\d]/g,'')}`}>{s.phone}</a><a href={`mailto:${s.email}`}>{s.email}</a><p>{s.address}</p><div className="actions">{[['Instagram',s.instagram],['Facebook',s.facebook],['LinkedIn',s.linkedin]].filter(([,url])=>url).map(([name,url])=><a href={url} key={name} target="_blank" rel="noopener noreferrer">{name}</a>)}</div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} {s.company}</span><div><Link href="/kvkk">KVKK</Link><Link href="/gizlilik-politikasi">Gizlilik</Link><Link href="/cerez-politikasi">Çerez Politikası</Link></div></div></footer><a className="floating-wa" href={wa} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp ile Rana Etiket’e yazın"><MessageCircle size={23}/><span>Birlikte üretelim</span></a><JsonLd data={{'@context':'https://schema.org','@type':['Organization','LocalBusiness'],'@id':`${siteUrl()}/#organization`,name:s.company,url:siteUrl(),logo:siteUrl()+s.logo,telephone:s.phone,email:s.email,address:{'@type':'PostalAddress',streetAddress:s.address,addressLocality:'İstanbul',addressCountry:'TR'}}}/></>;}
