import { PrismaClient } from '@prisma/client';
import { groups, sectors, featuredNames, capabilities, processSteps, blogSeeds } from '../lib/seed-data';
import { slugify, address } from '../lib/utils';
const db = new PrismaClient();
async function main() {
 const sectorImages=['/images/kozmetik-kutusu.webp','/images/gida-urun-kutusu.webp','/images/dokuma-etiket.webp','/images/ilac-medikal-urun-kutusu.webp','/images/e-ticaret-urun-kutusu.webp','/images/ozel-baskili-urun-kutusu.webp','/images/aksesuar-kutusu.webp','/images/katalog.webp'];
 for (const [i,s] of sectors.entries()) await db.sector.upsert({where:{slug:s[1]},update:{image:sectorImages[i]},create:{name:s[0],slug:s[1],description:s[2],image:sectorImages[i],sortOrder:i}});
 const sectorRows = await db.sector.findMany();
 for (const [gi,g] of groups.entries()) {
  const categoryImages=['/images/ozel-baskili-urun-kutusu.webp','/images/rulo-etiket.webp','/images/dokuma-etiket.webp','/images/katalog.webp','/images/karton-canta.webp','/images/size-ozel-uretim.webp'];
  const category = await db.category.upsert({where:{slug:g.slug},update:{image:categoryImages[gi]},create:{name:g.name,slug:g.slug,description:g.description,image:categoryImages[gi],sortOrder:gi}});
  for (const [i,name] of g.items.split('|').entries()) {
   const slug = slugify(name); const textile = gi===2; const woven = /Dokuma|Arma/.test(name); const wash = /Yıkama|Baskılı Tekstil/.test(name);
   const uses = textile ? ['Hazır giyim koleksiyonları','Ev tekstili','Aksesuar ve tekstil ürünleri'] : gi===0 ? [/Gıda|Çikolata|Lokum|Kurabiye|Pastane|Hamburger|Paket Servis/.test(name)?'Gıda sunumu ve ambalajlama':'Ürün sunumu','Markaya özel ambalaj','Perakende ve e-ticaret'] : gi===1 ? ['Ürün kimliklendirme','Ambalaj üzerinde bilgi sunumu','Marka ve seri bilgileri'] : gi===3 ? ['Kurumsal iletişim','Ürün ve hizmet tanıtımı','Mağaza ve etkinlik çalışmaları'] : ['Mağaza ve perakende','Hediye sunumu','Markalı teslimat'];
   const specs:Record<string,string> = {Malzeme:woven?'Tafta veya atkı saten dokuma; tasarıma göre değerlendirilir':wash?'Saten, siyah saten veya pamuklu kumaş; işe uygun seçenekler':textile?'Farklı kağıt ve karton kaliteleri; uygun işlerde PVC':gi===0?'Ürünün yapısına göre karton veya kraft seçenekleri':gi===1?(name.includes('PP')?'PP film':name.includes('Şeffaf')?'Şeffaf film':name.includes('Kraft')?'Kraft kağıt':'Kağıt veya film; yüzey koşullarına göre seçilir'):gi===4?'Kraft veya baskıya uygun kağıt / karton':'İşe uygun kağıt ve karton seçenekleri',Ebat:'Ürüne ve tasarıma özel ölçülendirme',Baskı:woven?'Dokuma desen ve renk çalışması':wash?'Okunaklı bakım bilgisi ve sembol baskısı':'Tasarıma ve malzemeye uygun baskı',Kesim:woven?'Sıcak kesim, lazer kesim':wash?'Sıcak veya soğuk kesim':gi===0?'Kutunun yapısına uygun özel bıçaklı kesim':'Düz veya özel form kesim','Minimum üretim':'Malzeme, ölçü ve uygulamaya göre teklif aşamasında belirlenir',Teslimat:'İşin kapsamı ve üretim planıyla birlikte netleştirilir'};
   if(woven) specs.Katlama='Orta, kenar veya kelebek katlama'; else if(wash) specs.Katlama='Orta katlama; ürüne uygun seçenekler'; else if(gi!==1) specs['Yüzey işlemleri']='Selefon, lak, varak veya gofre; malzeme uygunluğuna göre';
   const options = woven?['Tela ve kolalama','Bantlı uygulama','Parlatma ve kabartma','Arma ve özel form']:wash?['Kenar örgülü veya polyester saten','Ürüne özel bakım bilgileri','Sıcak / soğuk kesim']:textile?['Ofset veya serigraf baskı','İp ve iğne uygulaması','Sıvama ve özel kesim','Selefon, lak, varak veya kabartma']:gi===0?['Ölçü ve yapı geliştirme','Malzemeye uygun yüzey işlemleri','Katlama ve yapıştırma','Tasarım dosyası teknik kontrolü']:gi===1?['Yüzeye uygun yapışkan seçimi','Rulo veya tabaka hazırlığı','Özel form ve ölçülendirme','Barkod ve bilgi alanı kontrolü']:['Özel ölçü ve kağıt seçimi','Baskı ve renk hazırlığı','Uygun yüzey işlemleri','Teknik dosya kontrolü'];
   const relevant = textile?['tekstil']: /Kozmetik|Parfüm|Krem|Serum|Sabun/.test(name)?['kozmetik','perakende']: /Gıda|Çikolata|Lokum|Kurabiye|Pastane|Hamburger|Paket Servis|Kavanoz/.test(name)?['gida','perakende']: /Medikal/.test(name)?['medikal']:gi===3?['kurumsal','kozmetik','perakende']:['e-ticaret','perakende','taki-aksesuar','kozmetik'];
   const summary = `${name} üretimini ölçü, malzeme ve tasarım ihtiyaçlarınıza göre birlikte planlayalım.`;
   await db.product.upsert({where:{slug},update:{cover:`/images/${slug}.webp`,gallery:JSON.stringify([`/images/${slug}.webp`])},create:{name,slug,categoryId:category.id,summary,description:`${name}, markanızın ürünle kurduğu teması tamamlar. ${g.description} Tasarım dosyanızı, kullanım koşullarını ve planlanan adedi birlikte değerlendirerek projenize uygun üretim seçeneklerini netleştiriyoruz.`,cover:`/images/${slug}.webp`,gallery:JSON.stringify([`/images/${slug}.webp`]),alt:`${name} için Rana özgün tasarım görselleştirmesi`,specs:JSON.stringify(specs),uses:JSON.stringify(uses),options:JSON.stringify(options),seoTitle:`${name} Baskı ve Üretimi | Rana Etiket`,seoDescription:summary,sortOrder:gi*100+i,featured:featuredNames.includes(name),sectors:{connect:sectorRows.filter(s=>relevant.includes(s.slug)).map(s=>({id:s.id}))},faqs:{create:[{question:'Teklif almak için hangi bilgileri paylaşmalıyım?',answer:'Ürün ölçüsü, tahmini adet, kullanım alanı ve varsa tasarım dosyanız yeterli bir başlangıçtır. Kesinleşmeyen teknik ayrıntıları birlikte değerlendirebiliriz.',sortOrder:0},{question:'Minimum adet ve teslim süresi nedir?',answer:'Bu bilgiler malzemeye, ölçüye, uygulamalara ve üretim planına göre değişir. Projenize ait bilgileri ilettiğinizde teklif aşamasında netleştirilir.',sortOrder:1},{question:'Tasarım ve numune süreci nasıl ilerler?',answer:'Dosyanızın üretime uygunluğunu değerlendiriyoruz. Numune ihtiyacı ve mümkün olan kontrol yöntemi işin kapsamına göre ayrıca görüşülür.',sortOrder:2}]}}});
  }
 }
 const blogImages=['/images/ozel-baskili-urun-kutusu.webp','/images/rulo-etiket.webp','/images/premium-kartvizit.webp','/images/yaldizli-kartvizit.webp','/images/ozel-baskili-urun-kutusu.webp'];
 for(const [i,b] of blogSeeds.entries()) await db.blogPost.upsert({where:{slug:b.slug},update:{image:blogImages[i]},create:{...b,image:blogImages[i],alt:b.title}});
 const settings:Record<string,unknown>={company:'RANA ETİKET & MATBAA',tagline:'ETİKET • AMBALAJ • BASKI',logo:'/logo.svg',favicon:'/favicon.svg',phone:'+90 (212) 493 36 34',whatsapp:'+90 (535) 733 28 23',email:'ranaetiket@hotmail.com',address,mapTitle:'Rana Etiket — Topkapı, İstanbul',mapsUrl:'',mapsEmbed:'',latitude:'',longitude:'',yandex:'',instagram:'',facebook:'',linkedin:'',footer:'Tasarımdan üretime, markanıza özel baskı çözümleri.',analytics:'',seoTitle:'Rana Etiket & Matbaa | Kutu, Etiket ve Ambalaj Üretimi',seoDescription:'Markanıza özel kutu, etiket, tekstil etiketi, ambalaj ve kurumsal baskı çözümleri. Rana Etiket ile projenize uygun üretim seçeneklerini değerlendirin.',home:{eyebrow:'İSTANBUL’DAN, MARKANIZ İÇİN.',title:'Markanızı kutudan\nrafa taşıyoruz.',description:'Kutudan etikete, ilk fikirden son dokunuşa. Markanıza özel ambalaj ve baskı çözümlerini tek noktada hayata geçiriyoruz.',image:'/images/size-ozel-uretim.webp',ctaText:'Ürünleri keşfedin',ctaUrl:'/urunler',featuredTitle:'İyi bir izlenim,\ndoğru ürünle başlar.',categoryTitle:'Her detayda\nüretim bilgisi.',sectorTitle:'Sizin sektörünüz.\nBizim uzmanlığımız.',whyTitle:'Birlikte düşünür,\nözenle üretiriz.',whyText:'2002’de grafik tasarımla başlayan yolculuğumuzu, 2004’te kurduğumuz makine parkuruyla üretime taşıdık. Bugün tasarımdan teslimata kadar her adımı aynı özenle takip ediyoruz.',processTitle:'Fikirden ürüne,\naynı masanın etrafında.',process:processSteps,ctaTitle:'Bir projeniz mi var?',ctaDescription:'Ürününüzü, ölçünüzü ve adedinizi bize gönderin; size özel üretim seçeneklerini değerlendirelim.',featuredIds:[],categoryIds:[],sectorIds:[]},about:{title:'Baskının ötesinde,\nbir üretim ortaklığı.',text:'2002 yılında grafik tasarım alanında başlayan matbaacılık serüvenimiz, 2004 yılında makine parkurumuzun kurulmasıyla aktif üretime dönüştü.\n\nTekstil, plastik ve medikal sektörlerinin matbaa ve etiket ihtiyaçlarına hizmet verirken tasarımla üretimin birbirinden ayrı düşünülemeyeceğini öğrendik. Deneyimli kadromuzla dosya hazırlığından ürün teslimine kadar süreci takip ediyoruz.\n\nKaliteyi malzeme ve uygulama seçiminde, termini açık üretim planlamasında, fiyat yaklaşımımızı ise ihtiyaca uygun çözüm üretmekte arıyoruz.',values:[['Kalite','Doğru malzeme, özenli uygulama ve işin gerektirdiği kontroller.'],['Termin','Üretim ve teslim sürecinde açık iletişim ve birlikte yapılan planlama.'],['Fiyat','İhtiyacınızı karşılayan malzeme ve uygulamaları dengeli biçimde değerlendirme.']]},production:{title:'İyi tasarım,\ndoğru üretimle buluşur.',description:'Malzemeyi tanıyan, uygulamayı önemseyen bir yaklaşımla. Her işi kendi gereksinimleri içinde değerlendiriyoruz.',capabilities,machines:[]},menus:{header:[['Ana Sayfa','/'],['Ürünler','/urunler'],['Sektörler','/sektorler'],['Üretim','/uretim'],['Hakkımızda','/hakkimizda'],['Blog','/blog'],['İletişim','/iletisim']],footer:[['Hakkımızda','/hakkimizda'],['Üretim','/uretim'],['Blog','/blog'],['İletişim','/iletisim']]}};
 for(const [key,value] of Object.entries(settings)) await db.siteSetting.upsert({where:{key},update:{},create:{key,value:JSON.stringify(value)}});
 console.log(`Katalog hazır: ${await db.product.count()} ürün, ${await db.sector.count()} sektör, ${await db.blogPost.count()} yazı. Mevcut kayıtlar korunmuştur.`);
}
main().finally(()=>db.$disconnect());


