import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import type { Product, Category } from '@prisma/client';
import { whatsapp } from '@/lib/utils';
export function Heading({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}) {return <div className="section-heading">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{description&&<p className="muted">{description}</p>}</div>;}
export function ProductCard({product,phone}:{product:Product&{category?:Category};phone:string}) {return <article className="product-card"><Link href={`/urunler/${product.slug}`} className="product-image"><Image src={product.cover} alt={product.alt} fill sizes="(max-width:600px) 90vw,(max-width:1000px) 45vw,25vw"/><span className="round-arrow"><ArrowUpRight size={19}/></span></Link><div className="card-content"><span className="eyebrow">{product.category?.name}</span><h3><Link href={`/urunler/${product.slug}`}>{product.name}</Link></h3><p>{product.summary}</p><div className="card-actions"><Link href={`/urunler/${product.slug}`}>Ürünü incele <ArrowRight size={15}/></Link><a href={whatsapp(phone,product)} target="_blank" rel="noopener noreferrer">Teklif al <ArrowUpRight size={15}/></a></div></div></article>;}
export function QuoteCTA({phone,title='Bir projeniz mi var?',description='Ürününüzü, ölçünüzü ve adedinizi bize gönderin; size özel üretim seçeneklerini değerlendirelim.'}:{phone:string;title?:string;description?:string}){return <section className="quote-band"><div><p className="eyebrow">BİRLİKTE ÜRETELİM</p><h2>{title}</h2><p>{description}</p></div><div className="actions"><a className="button light" href={whatsapp(phone)} target="_blank" rel="noopener noreferrer">WhatsApp’tan teklif al <ArrowUpRight size={19}/></a><Link className="text-link" href="/teklif-al">Teklif formunu doldurun <ArrowRight size={18}/></Link></div></section>;}
export function Breadcrumbs({items}:{items:{name:string;href?:string}[]}){return <nav aria-label="İçerik yolu" className="breadcrumbs"><Link href="/">Ana Sayfa</Link>{items.map((i,n)=><span key={n}> / {i.href?<Link href={i.href}>{i.name}</Link>:<span aria-current="page">{i.name}</span>}</span>)}</nav>;}
export function JsonLd({data}:{data:Record<string,unknown>}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>;}
