import { createHmac,randomBytes,scryptSync,timingSafeEqual } from 'node:crypto';
import { cookies,headers } from 'next/headers';
import { db } from './db';
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
const cookieName='rana_admin';
function digest(token:string){const secret=process.env.AUTH_SECRET;if(!secret||secret.length<32)throw new HttpError(503,'Yönetici yapılandırması tamamlanmamış.');return createHmac('sha256',secret+(process.env.ADMIN_PASSWORD||'')).update(token).digest('hex');}
export async function getSession(){const token=(await cookies()).get(cookieName)?.value;if(!token)return null;const session=await db.adminSession.findUnique({where:{id:digest(token)}});return session&&session.expiresAt>new Date()&&session.email===process.env.ADMIN_EMAIL?session:null;}
export async function requireAdmin(){const session=await getSession();if(!session)throw new HttpError(401,'Lütfen yönetici girişi yapın.');return session;}
export async function startSession(email:string,password:string){const expected=process.env.ADMIN_PASSWORD,admin=process.env.ADMIN_EMAIL;if(!expected||expected.length<12||!admin)throw new HttpError(503,'Yönetici hesabı .env içinde yapılandırılmalı.');const salt=process.env.AUTH_SECRET||'';const valid=timingSafeEqual(scryptSync(password,salt,64),scryptSync(expected,salt,64));if(!valid||email.toLowerCase()!==admin.toLowerCase())throw new HttpError(401,'E-posta veya şifre hatalı.');const token=randomBytes(32).toString('base64url'),expiresAt=new Date(Date.now()+8*3600000);await db.adminSession.deleteMany({where:{expiresAt:{lt:new Date()}}});await db.adminSession.create({data:{id:digest(token),email:admin,expiresAt}});(await cookies()).set(cookieName,token,{httpOnly:true,secure:process.env.COOKIE_SECURE==='true',sameSite:'strict',path:'/',expires:expiresAt});}
export async function endSession(){const c=await cookies(),token=c.get(cookieName)?.value;if(token)await db.adminSession.deleteMany({where:{id:digest(token)}});c.delete(cookieName);}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');const requestOrigin=new URL(request.url).origin;const siteOrigin=process.env.SITE_URL?new URL(process.env.SITE_URL).origin:null;if(!origin||(origin!==requestOrigin&&origin!==siteOrigin))throw new HttpError(403,'İstek kaynağı doğrulanamadı.');}
export async function rateLimit(scope:string,limit:number,windowMs:number){const h=await headers();const ip=process.env.TRUST_PROXY==='true'?(h.get('x-forwarded-for')?.split(',')[0].trim()||'unknown'):'local';const key=`${scope}:${createHmac('sha256',process.env.AUTH_SECRET||'rate-limit').update(ip).digest('hex')}`;const now=new Date();await db.rateLimit.deleteMany({where:{expiresAt:{lt:now}}});const row=await db.rateLimit.upsert({where:{key},create:{key,count:1,expiresAt:new Date(Date.now()+windowMs)},update:{count:{increment:1}}});if(row.count>limit)throw new HttpError(429,'Çok fazla istek gönderdiniz. Lütfen daha sonra yeniden deneyin.');}
export function apiError(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status});if(error instanceof Error&&error.name==='ZodError')return Response.json({error:'Lütfen gerekli alanları, bağlantıları ve dosya bilgilerini kontrol edin.'},{status:400});if(error instanceof Error&&'code'in error){if(error.code==='P2002')return Response.json({error:'Bu adres (slug) zaten kullanılıyor.'},{status:409});if(error.code==='P2003')return Response.json({error:'Bu kayda bağlı ürünler var. Önce ürünleri başka kategoriye taşıyın.'},{status:409});}console.error(error);return Response.json({error:'İşlem tamamlanamadı. Lütfen yeniden deneyin.'},{status:500});}
