export const groups = [
 {name:'Kutu & Ambalaj',slug:'kutu-ambalaj',description:'Ürününüzün yapısına, raf koşullarına ve marka diline uygun kutu çözümleri.',items:'Özel Baskılı Ürün Kutusu|Kozmetik Kutusu|Parfüm Kutusu|Krem Kutusu|Serum Kutusu|Sabun Kutusu|İlaç / Medikal Ürün Kutusu|Gıda Ürün Kutusu|Çikolata Kutusu|Lokum Kutusu|Kurabiye Kutusu|Pastane Kutusu|Hamburger Kutusu|Paket Servis Kutusu|E-Ticaret Ürün Kutusu|Kargo Kutusu|Kraft Kutu|Pencereli Kutu|Askılı Kutu|Kilitli Kutu|Özel Kesim Kutu|Karton Ambalaj Kutusu|Hediye Kutusu|Tekstil Ürün Kutusu|Aksesuar Kutusu'},
 {name:'Etiket & Sticker',slug:'etiket-sticker',description:'Ambalajınızla bütünleşen, okunaklı ve uygulama yüzeyine uygun etiketler.',items:'Rulo Etiket|Kuşe Etiket|PP Etiket|Şeffaf Etiket|Kraft Etiket|Opak Etiket|Ürün Etiketi|Gıda Etiketi|Kozmetik Etiketi|Şişe Etiketi|Kavanoz Etiketi|Ambalaj Etiketi|Barkod Etiketi|Özel Kesim Sticker|Yuvarlak Sticker|Etiket / Sticker Setleri|Gıda Ambalajı Kuşak Etiketi'},
 {name:'Tekstil Etiketleri',slug:'tekstil-etiketleri',description:'Koleksiyonunuzun kimliğini taşıyan karton, dokuma ve bakım etiketleri.',items:'Karton Etiket|Sallantı Kartı|Beden Kartı|Cep Karton Etiketi|Şerit Karton Etiket|Dokuma Etiket|Tafta Dokuma Etiket|Saten Dokuma Etiket|Yıkama Talimatı|Saten Yıkama Talimatı|Siyah Saten Yıkama Talimatı|Pamuklu Yıkama Talimatı|Lazer Kesim Etiket|Dokuma Arma|Baskılı Tekstil Etiketi'},
 {name:'Kurumsal Matbaa',slug:'kurumsal-matbaa',description:'Markanızın her temas noktasında tutarlı bir görünüm sunan baskılı işler.',items:'Kartvizit|Premium Kartvizit|Laklı Kartvizit|Yaldızlı Kartvizit|Sıvamalı Kartvizit|Broşür|Kırımlı Broşür|El İlanı|Katalog|Dergi|Insert / İnsört|Antetli Kağıt|Diplomat Zarf|Torba Zarf|Cepli Dosya|Bloknot|Defter|Afiş / Poster|Magnet|Davetiye|Menü|Adisyon|Sipariş Fişi / Makbuz|Sözleşme Formu'},
 {name:'Çanta & Taşıma',slug:'canta-tasima',description:'Mağazadan teslimata, markanızın görünürlüğünü sürdüren taşıma ambalajları.',items:'Karton Çanta|Kraft Karton Çanta|Premium Karton Çanta|Özel Baskılı Mağaza Çantası|Hediye Çantası'},
 {name:'Özel Üretim',slug:'ozel-uretim',description:'Standartların dışında bir fikriniz varsa, doğru üretim yöntemini birlikte bulalım.',items:'Size Özel Üretim'}
];
export const sectors = [
 ['Kozmetik','kozmetik','Kutu, etiket ve tamamlayıcı baskıları aynı marka dili etrafında buluşturuyoruz.'],
 ['Gıda','gida','Ürün sunumunu güçlendiren ambalajları kullanım koşulları ve temas gereksinimleriyle birlikte değerlendiriyoruz.'],
 ['Tekstil','tekstil','Koleksiyonunuzun karakterini karton etiket, dokuma etiket ve yıkama talimatlarına taşıyoruz.'],
 ['Medikal & Sağlık','medikal','Ürün bilgisinin açık ve okunaklı sunulduğu kutu, etiket ve basılı doküman çözümleri.'],
 ['E-Ticaret','e-ticaret','Teslimat deneyimini tamamlayan kutular, etiketler ve paket içi basılı materyaller.'],
 ['Perakende','perakende','Raf, mağaza ve alışveriş deneyimi boyunca markanızın bütünlüğünü koruyan üretimler.'],
 ['Takı & Aksesuar','taki-aksesuar','Küçük detaylara değer veren ürünler için özenli kutu, kart ve taşıma çözümleri.'],
 ['Kurumsal Firmalar','kurumsal','Tanıtım, iletişim ve günlük iş süreçleri için birbiriyle uyumlu basılı materyaller.']
];
export const featuredNames = ['Kozmetik Kutusu','Özel Baskılı Ürün Kutusu','Kraft Kutu','Karton Etiket','Rulo Etiket','Dokuma Etiket','Yıkama Talimatı','Karton Çanta','Broşür','Katalog','Özel Kesim Sticker','Gıda Ürün Kutusu'];
export const capabilities = [
 ['Ofset Baskı','Karton ve kağıt işlerinizde tasarım, renk ve malzeme ilişkisini birlikte ele alan baskı hazırlığı.'],
 ['Serigraf Baskı','Uygun malzemelerde, tasarımınızın gerektirdiği özel baskı etkileri için değerlendirilir.'],
 ['Özel Kesim','Kutunun yapısına veya etiketin formuna göre şekilli ve bıçaklı kesim çözümleri.'],
 ['Lazer Kesim','Malzeme ve tasarım uygunluğuna göre hassas form ve detayların oluşturulması.'],
 ['Selefon','Mat veya parlak yüzey etkisiyle baskının görünümünü ve kullanım hissini tamamlar.'],
 ['Lak & Lokal Lak','Tüm yüzeyde veya seçilmiş detaylarda kontrollü parlaklık ve görsel vurgu.'],
 ['Varak / Yaldız','Logo ve seçilmiş grafik alanlarında metalik vurgu seçenekleri.'],
 ['Gofre / Kabartma','Kağıt ve kartonda dokunsal detaylar oluşturmak için kabartma uygulamaları.'],
 ['Sıvama','Farklı kağıt veya karton katmanlarını birleştirerek yapıyı ve yüzey hissini geliştirme.'],
 ['Katlama & Yapıştırma','Kesilmiş yüzeyleri tasarlanan ürün formuna dönüştüren tamamlayıcı işlemler.'],
 ['Giyotin & Kesim','İşe uygun giyotin, sıcak veya soğuk kesim yöntemiyle ölçülendirme.'],
 ['Tekstil Etiketi Üretimi','Dokuma, baskı, katlama ve uygulama seçeneklerini ürünün kullanımına göre planlama.']
];
export const processSteps = [
 ['İhtiyacı dinliyoruz','Ürününüzü, ölçüyü, adedi ve kullanım amacını birlikte netleştiriyoruz.'],
 ['Teknik hazırlık','Tasarım dosyasını, malzemeyi ve baskı seçeneklerini değerlendiriyoruz.'],
 ['Kontrol ve onay','Üretim öncesi detayları onayınıza sunuyor; numune ihtiyacını projeye göre değerlendiriyoruz.'],
 ['Üretim','Onaylanan özellikleri baskı, kesim ve tamamlayıcı uygulamalara taşıyoruz.'],
 ['Teslimat','Üretim ve teslim planını işin kapsamına göre sizinle paylaşıyoruz.']
];
export const blogSeeds = [
 {title:'Ürün Kutusu Tasarlarken Nelere Dikkat Edilmeli?',slug:'urun-kutusu-tasarimi',excerpt:'İyi bir kutu tasarımı, görsel kimlik kadar ürünün ölçüsü ve kullanım biçimiyle de başlar.',content:`Önce ürünü tanıyın\nKutu tasarımının başlangıç noktası ürünün kendisidir. En, boy ve yükseklik ölçülerinin yanında ağırlık, kırılganlık ve ambalaja yerleştirme biçimi de belirlenmelidir. Ölçüleri yalnızca dış görünüşe göre seçmek, ürünün kutu içinde hareket etmesine veya gereksiz malzeme kullanımına yol açabilir.\n\nKullanım senaryosunu belirleyin\nRafta sergilenecek bir kutu ile kargoya verilecek ambalaj aynı ihtiyaçları taşımaz. Raf üzerinde okunabilirlik ve yüzey görünümü öne çıkarken, taşıma koşullarında yapısal dayanım ayrıca değerlendirilir. İç destek gerekip gerekmediğini ürünün yapısıyla birlikte ele alın.\n\nTasarımı kesim çizgisiyle birlikte düşünün\nLogo, ürün adı ve zorunlu bilgileri katlama veya yapıştırma alanlarından uzak tutun. Kesim çizgisi üzerindeki çalışma payları, taşma ve güvenli alan değerleri işi üretecek ekiple kesinleştirilmelidir. Ekrandaki renklerle baskı sonucunun aynı görünmeyebileceğini unutmayın.\n\nMalzeme ve yüzey kararlarını birlikte verin\nMat selefon, lokal lak veya varak gibi uygulamalar tasarımı desteklediğinde anlam kazanır. Her uygulamanın seçilen kartona ve kullanım biçimine uygunluğunu kontrol edin. Bütün yüzeyi işlemle kaplamak yerine önemli bir ayrıntıyı vurgulamak daha dengeli bir sonuç verebilir.\n\nTeklif için kısa bir üretim özeti hazırlayın\nÜrün ölçüsü, planlanan adet, kullanım alanı ve varsa tasarım dosyanız iyi bir başlangıçtır. Kesinleştirmediğiniz ayrıntıları ayrıca belirtin. Rana ile bu bilgiler üzerinden malzeme ve üretim seçeneklerini değerlendirebilirsiniz.`},
 {title:'Doğru Etiket Malzemesi Nasıl Seçilir?',slug:'etiket-malzemesi-secimi',excerpt:'Yüzey, nem, sıcaklık ve kullanım süresi: etiket malzemesi seçiminde birlikte değerlendirilmesi gereken dört konu.',content:`Etiketin uygulanacağı yüzey\nCam, plastik, karton ve tekstil aynı yüzey davranışını göstermez. Yüzeyin düz ya da eğimli olması, temizliği ve uygulama yöntemi yapışkan seçimini etkiler. Bu nedenle yalnızca etiket ölçüsünü bilmek yeterli değildir; kullanılacağı ambalaj örneği de değerlendirmeye yardımcı olur.\n\nKağıt ve film seçenekleri\nKuşe ve kraft gibi kağıt seçenekleri farklı görsel karakterler sunar. PP ve şeffaf film türleri ise belirli kullanım koşullarında değerlendirilebilir. Bir malzemenin adı tek başına suya, kimyasala veya sıcaklığa dayanıklılık garantisi değildir. Yapışkan, baskı ve yüzey işlemi birlikte seçilmelidir.\n\nOkunabilirliği koruyun\nÜrün adı, içerik bilgisi ve barkod için yeterli alan bırakın. Şeffaf zemin üzerinde baskı planlanıyorsa ambalaj renginin okunabilirliğe etkisini inceleyin. Barkodun son boyutta okunması ve baskı kontrastı ayrıca kontrol edilmelidir.\n\nUygulama biçimini paylaşın\nElle uygulanacak etiketlerle otomatik makinede kullanılacak rulo etiketlerin hazırlığı farklı olabilir. Rulo sarım yönü, iç çap ve dış çap gibi gereksinimleri uygulama ekipmanınıza göre üreticiyle netleştirin.\n\nKoşulları birlikte değerlendirin\nEtiket talebinizde ambalaj malzemesini, ortamı ve planlanan adedi belirtin. Gıda veya medikal kullanımda gerekli uygunluk belgelerini ve uygulama koşullarını ayrıca görüşün. Kesin malzeme kararını bu değerlendirme sonrasında vermek, yeniden üretim riskini azaltır.`},
 {title:'Mat Selefon ve Parlak Selefon Arasındaki Farklar',slug:'mat-ve-parlak-selefon',excerpt:'Yüzey hissi ve görsel etki açısından iki uygulamayı ürününüzün bağlamında değerlendirin.',content:`Yüzeyin tasarıma etkisi\nSelefon, baskılı kağıt veya kartonun yüzeyine film uygulanmasıdır. Mat ve parlak seçenekler aynı tasarımın farklı algılanmasına neden olabilir. Seçimi yalnızca ekrandaki görsele göre değil, mümkün olduğunda baskılı yüzey örneği üzerinden yapmak yararlıdır.\n\nMat selefonun görünümü\nMat yüzey ışığı daha yumuşak dağıtan bir görünüm sunar. Sade tipografi ve geniş renk alanlarında tercih edilebilir. Bununla birlikte koyu zeminlerde iz ve yüzey hassasiyeti malzeme türüne göre farklılık gösterebilir; kullanım koşullarını üreticiyle değerlendirin.\n\nParlak selefonun görünümü\nParlak yüzey ışığı daha belirgin yansıtır ve renklerin algısını etkiler. Yoğun görsel kullanılan ambalajlarda değerlendirilebilir. Güçlü aydınlatma altında küçük yazıların okunabilirliğini korumak için tasarımın son boyutunu kontrol edin.\n\nDiğer uygulamalarla uyum\nLokal lak, varak veya gofre planlanıyorsa film ve uygulama sırası birlikte ele alınmalıdır. Her kombinasyon bütün malzemelerde aynı sonucu vermez. Katlama alanlarında yüzey davranışı da kontrol edilmelidir.\n\nNasıl karar verilmeli?\nÜrününüzün raf ortamı, hedeflenen yüzey hissi, tasarım yoğunluğu ve bütçe birlikte değerlendirilmelidir. Teklif talebinizde düşündüğünüz seçeneği belirtin; kararsızsanız kullanım amacını paylaşarak alternatifleri görüşün.`},
 {title:'Varak, Lak ve Gofre Nedir?',slug:'varak-lak-gofre',excerpt:'Birbirinden farklı üç yüzey uygulaması ve tasarımda hangi amaçlarla kullanılabilecekleri.',content:`Varak ile seçilmiş vurgu\nVarak, logo veya grafik detaylarında metalik görünüm elde etmek için değerlendirilen bir uygulamadır. Çok ince çizgiler, küçük metinler ve geniş yüzeyler farklı üretim gereksinimleri doğurabilir. Tasarım dosyasındaki varak alanlarını ayrı tanımlamak teknik hazırlığı kolaylaştırır.\n\nLak ve lokal lak\nLak yüzeyin tamamına veya belirli bir bölümüne uygulanabilir. Lokal lakta seçilmiş bir alanın parlaklık farkıyla öne çıkması amaçlanır. Bu etki, zemin ve diğer yüzey işlemleriyle birlikte tasarlandığında daha belirgin hale gelir.\n\nGofre ve dokunsal etki\nGofre, malzemede kabartma etkisi oluşturmak için kullanılır. Sonucun belirginliği kağıdın yapısına, tasarımın detayına ve uygulama biçimine bağlıdır. Ambalajın arka yüzündeki görünüm ve ürünün yapısı da tasarım sırasında dikkate alınmalıdır.\n\nHer detaya işlem gerekmez\nÜç uygulamayı aynı işte kullanmak zorunlu değildir. Markanın önemli bir unsurunu seçip ona odaklanmak daha tutarlı olabilir. Birden fazla uygulama düşünülüyorsa hizalama toleransları ve üretim sırası teknik ekip tarafından değerlendirilmelidir.\n\nDosyanızı nasıl hazırlamalısınız?\nBaskı görseliyle özel uygulama alanlarını ayrı katmanlarda sunun. Kesin çizgi kalınlıkları ve dosya biçimini üretim öncesinde doğrulayın. Rana ile malzeme, tasarım ve uygulama seçeneklerini projeniz üzerinden konuşabilirsiniz.`},
 {title:'Markalar İçin Ambalaj Tasarımının Önemi',slug:'markalar-icin-ambalaj',excerpt:'Tutarlı bir ambalaj dili, ürünle kurulan ilk teması ve kullanım deneyimini destekler.',content:`İlk temasın bir parçası\nAmbalaj, ürün hakkında bilgi veren ve markanın dilini taşıyan bir yüzeydir. Ürün adı, tipografi, renk ve malzeme aynı bütüne hizmet ettiğinde kullanıcının ürünü anlaması kolaylaşır. Tasarımın temel görevi yalnızca dikkat çekmek değildir; doğru bilgiyi açık biçimde sunmaktır.\n\nÜrün ailesi içinde tutarlılık\nFarklı boyut veya çeşitlerdeki ürünlerin ambalajları ortak bir sistemle tasarlanabilir. Logo konumu, bilgi sırası ve renk kullanımı için tutarlı kurallar oluşturmak yeni ürünlerin seriye eklenmesini kolaylaştırır. Çeşitleri ayırt etmek için tek başına renge güvenmeyin; okunaklı isimler de kullanın.\n\nAçılma ve kullanım deneyimi\nBir kutunun açılma biçimi, etiketin yerleşimi ve bilgilerin okunabilirliği tasarımın parçasıdır. Ürünün kutuya nasıl yerleştirileceği ve kullanıcının nasıl çıkaracağı önceden düşünülmelidir. Estetik kararların işlevi zorlaştırmaması gerekir.\n\nBaskıdan önce üretilebilirlik\nEkranda etkileyici görünen bir tasarımın seçilen malzemede uygulanabilir olması önemlidir. Kesim, katlama ve yüzey işlemlerini tasarımın sonuna bırakmak yerine sürece erken dahil edin. Böylece görsel beklentiyle üretim yöntemi arasındaki uyum daha kolay kurulur.\n\nBirlikte planlama\nMarkanızın görsel rehberi, ürün bilgileri ve kullanım senaryosu üretim görüşmesinin temelini oluşturur. Rana, bu çerçeve üzerinden kutu, etiket, çanta ve diğer baskılı ürünleri birlikte değerlendirmenize yardımcı olur.`}
];
