import { z } from 'zod';
import { db } from '@/lib/db';
import { productSchema,categorySchema,sectorSchema,blogSchema,settingSchemas,stringSettings } from '@/lib/validation';
import { requireAdmin,sameOrigin,apiError,HttpError } from '@/lib/security';
import { storage } from '@/lib/storage';
type Context={params:Promise<{entity:string}>};
export async function POST(request:Request,{params}:Context){try{sameOrigin(request);await requireAdmin();const {entity}=await params;if(Number(request.headers.get('content-length'))>9*1024*1024)throw new HttpError(413,'İstek çok büyük.');
 if(entity==='media'){const form=await request.formData(),file=form.get('file');if(!(file instanceof File))throw new HttpError(400,'Görsel seçin.');const stored=await storage.save(file);try{const media=await db.media.create({data:{...stored,alt:String(form.get('alt')||stored.name).slice(0,200)}});return Response.json(media,{status:201});}catch(e){await storage.remove(stored.url);throw e;}}
 const body=await request.json(),id=typeof body.id==='string'?body.id:undefined;let result:unknown;
 if(entity==='products'){const {gallery,specs,uses,options,related,sectorIds,faqs,...fields}=productSchema.parse(body);const data={...fields,gallery:JSON.stringify(gallery),specs:JSON.stringify(specs),uses:JSON.stringify(uses),options:JSON.stringify(options),related:JSON.stringify(related)};result=await db.$transaction(async tx=>{const faqData={faqs:{create:faqs.map((f,i)=>({...f,sortOrder:i}))}};if(id){await tx.fAQ.deleteMany({where:{productId:id}});return tx.product.update({where:{id},data:{...data,...faqData,sectors:{set:sectorIds.map(x=>({id:x}))}}});}return tx.product.create({data:{...data,...faqData,sectors:{connect:sectorIds.map(x=>({id:x}))}}});});}
 else if(entity==='categories'){const data=categorySchema.parse(body);if(data.parentId){let ancestor:string|null=data.parentId;const seen=new Set<string>();while(ancestor){if(ancestor===id||seen.has(ancestor))throw new HttpError(400,'Kategori döngüsü oluşturulamaz.');seen.add(ancestor);const row:{parentId:string|null}|null=await db.category.findUnique({where:{id:ancestor},select:{parentId:true}});if(!row)throw new HttpError(400,'Üst kategori bulunamadı.');ancestor=row.parentId;}}result=id?await db.category.update({where:{id},data:{...data,parentId:data.parentId||null}}):await db.category.create({data:{...data,parentId:data.parentId||null}});}
 else if(entity==='sectors'){const data=sectorSchema.parse(body);result=id?await db.sector.update({where:{id},data}):await db.sector.create({data});}
 else if(entity==='blog'){const data=blogSchema.parse(body);result=id?await db.blogPost.update({where:{id},data}):await db.blogPost.create({data});}
 else if(entity==='quotes'){const data=z.object({status:z.enum(['Yeni','Görüşülüyor','Teklif Verildi','Tamamlandı','İptal']),notes:z.string().max(10000)}).parse(body);if(!id)throw new HttpError(400,'Talep seçilmedi.');result=await db.quoteRequest.update({where:{id},data});}
 else if(entity==='settings'){const {key,value}=body;if(typeof key==='string'&&settingSchemas[key]){const parsed=settingSchemas[key].parse(value);result=await db.siteSetting.upsert({where:{key},create:{key,value:JSON.stringify(parsed)},update:{value:JSON.stringify(parsed)}});}else if(key==='general'){const parsed=stringSettings.parse(value);result=await db.$transaction(Object.entries(parsed).map(([key,value])=>db.siteSetting.upsert({where:{key},create:{key,value:JSON.stringify(value)},update:{value:JSON.stringify(value)}})));}else throw new HttpError(400,'Geçersiz ayar alanı.');}
 else throw new HttpError(404,'İşlem bulunamadı.');return Response.json({ok:true,result});}catch(e){return apiError(e);}}
export async function PATCH(request:Request,{params}:Context){try{sameOrigin(request);await requireAdmin();const {entity}=await params;const body=await request.json();if(entity==='media'){const {id,name,alt}=z.object({id:z.string(),name:z.string().min(1).max(200),alt:z.string().min(1).max(200)}).parse(body);await db.media.update({where:{id},data:{name,alt}});}else throw new HttpError(404,'İşlem bulunamadı.');return Response.json({ok:true});}catch(e){return apiError(e);}}
export async function DELETE(request:Request,{params}:Context){try{sameOrigin(request);await requireAdmin();const {entity}=await params;const {id}=z.object({id:z.string().min(1)}).parse(await request.json());if(entity==='products')await db.product.delete({where:{id}});else if(entity==='categories'){if(await db.category.count({where:{parentId:id}}))throw new HttpError(409,'Önce alt kategorileri taşıyın.');await db.category.delete({where:{id}});}else if(entity==='sectors')await db.sector.delete({where:{id}});else if(entity==='blog')await db.blogPost.delete({where:{id}});else if(entity==='quotes'){const quote=await db.quoteRequest.findUnique({where:{id}});await db.quoteRequest.delete({where:{id}});if(quote?.attachment)await storage.remove(quote.attachment);}else if(entity==='media'){const media=await db.media.findUnique({where:{id}});if(!media)throw new HttpError(404,'Görsel bulunamadı.');const [p,c,s,b,settings]=await Promise.all([db.product.count({where:{OR:[{cover:media.url},{gallery:{contains:media.url}}]}}),db.category.count({where:{image:media.url}}),db.sector.count({where:{image:media.url}}),db.blogPost.count({where:{image:media.url}}),db.siteSetting.count({where:{value:{contains:media.url}}})]);if(p+c+s+b+settings)throw new HttpError(409,'Bu görsel kullanımda. Önce ilgili içerikten kaldırın.');await storage.remove(media.url);await db.media.delete({where:{id}});}else throw new HttpError(404,'İşlem bulunamadı.');return Response.json({ok:true});}catch(e){return apiError(e);}}
